#pragma once
void sortingExercise();
void readAlgorithmExercise();
void lambdaExercise();
void minMaxExercise();
void writeOnlyExercise();
void replaceExercise();
void removeExercise();
void copyExercise();
